// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: scanner/Scanner.flex

package scanner;

import java_cup.runtime.*;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\41\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200"+
    "\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\1\u0100"+
    "\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u1f00"+
    "\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800"+
    "\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u1f00\1\u4d00\1\u4e00\1\u4f00"+
    "\1\u5000\3\u0100\1\u5100\1\u5200\1\u5300\12\u1f00\4\u0100\1\u5400"+
    "\17\u1f00\2\u0100\1\u5500\41\u1f00\2\u0100\1\u5600\1\u5700\2\u1f00"+
    "\1\u5800\1\u5900\27\u0100\1\u5a00\2\u0100\1\u5b00\45\u1f00\1\u0100"+
    "\1\u5c00\1\u5d00\11\u1f00\1\u5e00\24\u1f00\1\u5f00\1\u6000\1\u1f00"+
    "\1\u6100\1\u6200\1\u6300\1\u6400\2\u1f00\1\u6500\5\u1f00\1\u6600"+
    "\1\u6700\1\u6800\5\u1f00\1\u6900\1\u6a00\2\u1f00\1\u6b00\1\u1f00"+
    "\1\u6c00\21\u1f00\246\u0100\1\u6d00\20\u0100\1\u6e00\1\u6f00\25\u0100"+
    "\1\u7000\34\u0100\1\u7100\14\u1f00\2\u0100\1\u7200\u0b05\u1f00\1\u7300"+
    "\1\u7400\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\16\0\4\3"+
    "\1\1\1\5\1\6\1\3\1\7\1\10\1\11\1\3"+
    "\2\10\1\12\1\13\1\10\1\13\1\14\1\15\1\16"+
    "\11\17\1\3\1\10\1\5\1\20\1\5\2\3\1\21"+
    "\3\22\1\23\1\22\2\7\1\24\2\7\1\25\1\7"+
    "\1\26\1\7\1\27\1\7\1\30\5\7\1\31\2\7"+
    "\1\10\1\32\1\10\1\3\1\7\1\3\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\7"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\7\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\61\1\7"+
    "\1\10\1\62\1\10\1\3\41\0\2\3\4\7\4\3"+
    "\1\7\2\3\1\0\7\3\1\7\4\3\1\7\5\3"+
    "\27\7\1\3\37\7\1\3\u01ca\7\4\3\14\7\16\3"+
    "\5\7\7\3\1\7\1\3\1\7\21\3\160\0\5\7"+
    "\1\3\2\7\2\3\4\7\1\3\1\7\6\3\1\7"+
    "\1\3\3\7\1\3\1\7\1\3\24\7\1\3\123\7"+
    "\1\3\213\7\1\3\5\0\2\3\246\7\1\3\46\7"+
    "\2\3\1\7\6\3\51\7\6\3\1\7\1\3\55\0"+
    "\1\3\1\0\1\3\2\0\1\3\2\0\1\3\1\0"+
    "\10\3\33\7\4\3\4\7\15\3\6\0\5\3\1\7"+
    "\4\3\13\0\1\3\1\0\3\3\53\7\37\0\4\3"+
    "\2\7\1\0\143\7\1\3\1\7\10\0\1\3\6\0"+
    "\2\7\2\0\1\3\4\0\2\7\12\0\3\7\2\3"+
    "\1\7\17\3\1\0\1\7\1\0\36\7\33\0\2\3"+
    "\131\7\13\0\1\7\16\3\12\0\41\7\11\0\2\7"+
    "\4\3\1\7\2\3\1\0\30\7\4\0\1\7\11\0"+
    "\1\7\3\0\1\7\5\0\22\3\31\7\3\0\4\3"+
    "\13\7\65\3\25\7\1\3\10\7\25\3\61\0\66\7"+
    "\3\0\1\7\22\0\1\7\7\0\12\7\2\0\2\3"+
    "\12\0\1\3\20\7\3\0\1\3\10\7\2\3\2\7"+
    "\2\3\26\7\1\3\7\7\1\3\1\7\3\3\4\7"+
    "\2\3\1\0\1\7\7\0\2\3\2\0\2\3\3\0"+
    "\1\7\10\3\1\0\4\3\2\7\1\3\3\7\2\0"+
    "\2\3\12\0\4\7\7\3\2\7\1\3\1\0\2\3"+
    "\3\0\1\3\6\7\4\3\2\7\2\3\26\7\1\3"+
    "\7\7\1\3\2\7\1\3\2\7\1\3\2\7\2\3"+
    "\1\0\1\3\5\0\4\3\2\0\2\3\3\0\3\3"+
    "\1\0\7\3\4\7\1\3\1\7\7\3\14\0\3\7"+
    "\1\0\13\3\3\0\1\3\11\7\1\3\3\7\1\3"+
    "\26\7\1\3\7\7\1\3\2\7\1\3\5\7\2\3"+
    "\1\0\1\7\10\0\1\3\3\0\1\3\3\0\2\3"+
    "\1\7\17\3\2\7\2\0\2\3\12\0\1\3\1\7"+
    "\7\3\1\7\6\0\1\3\3\0\1\3\10\7\2\3"+
    "\2\7\2\3\26\7\1\3\7\7\1\3\2\7\1\3"+
    "\5\7\2\3\1\0\1\7\7\0\2\3\2\0\2\3"+
    "\3\0\10\3\2\0\4\3\2\7\1\3\3\7\2\0"+
    "\2\3\12\0\1\3\1\7\20\3\1\0\1\7\1\3"+
    "\6\7\3\3\3\7\1\3\4\7\3\3\2\7\1\3"+
    "\1\7\1\3\2\7\3\3\2\7\3\3\3\7\3\3"+
    "\14\7\4\3\5\0\3\3\3\0\1\3\4\0\2\3"+
    "\1\7\6\3\1\0\16\3\12\0\11\3\1\7\6\3"+
    "\5\0\10\7\1\3\3\7\1\3\27\7\1\3\20\7"+
    "\3\3\1\7\7\0\1\3\3\0\1\3\4\0\7\3"+
    "\2\0\1\3\3\7\5\3\2\7\2\0\2\3\12\0"+
    "\20\3\1\7\3\0\1\3\10\7\1\3\3\7\1\3"+
    "\27\7\1\3\12\7\1\3\5\7\2\3\1\0\1\7"+
    "\7\0\1\3\3\0\1\3\4\0\7\3\2\0\7\3"+
    "\1\7\1\3\2\7\2\0\2\3\12\0\1\3\2\7"+
    "\15\3\4\0\1\3\10\7\1\3\3\7\1\3\51\7"+
    "\2\0\1\7\7\0\1\3\3\0\1\3\4\0\1\7"+
    "\5\3\3\7\1\0\7\3\3\7\2\0\2\3\12\0"+
    "\12\3\6\7\2\3\2\0\1\3\22\7\3\3\30\7"+
    "\1\3\11\7\1\3\1\7\2\3\7\7\3\3\1\0"+
    "\4\3\6\0\1\3\1\0\1\3\10\0\6\3\12\0"+
    "\2\3\2\0\15\3\60\7\1\0\2\7\7\0\4\3"+
    "\10\7\10\0\1\3\12\0\47\3\2\7\1\3\1\7"+
    "\1\3\5\7\1\3\30\7\1\3\1\7\1\3\12\7"+
    "\1\0\2\7\11\0\1\7\2\3\5\7\1\3\1\7"+
    "\1\3\6\0\2\3\12\0\2\3\4\7\40\3\1\7"+
    "\27\3\2\0\6\3\12\0\13\3\1\0\1\3\1\0"+
    "\1\3\1\0\4\3\2\0\10\7\1\3\44\7\4\3"+
    "\24\0\1\3\2\0\5\7\13\0\1\3\44\0\11\3"+
    "\1\0\71\3\53\7\24\0\1\7\12\0\6\3\6\7"+
    "\4\0\4\7\3\0\1\7\3\0\2\7\7\0\3\7"+
    "\4\0\15\7\14\0\1\7\17\0\2\3\46\7\1\3"+
    "\1\7\5\3\1\7\2\3\53\7\1\3\115\7\1\3"+
    "\4\7\2\3\7\7\1\3\1\7\1\3\4\7\2\3"+
    "\51\7\1\3\4\7\2\3\41\7\1\3\4\7\2\3"+
    "\7\7\1\3\1\7\1\3\4\7\2\3\17\7\1\3"+
    "\71\7\1\3\4\7\2\3\103\7\2\3\3\0\40\3"+
    "\20\7\20\3\126\7\2\3\6\7\3\3\u016c\7\2\3"+
    "\21\7\1\3\32\7\5\3\113\7\3\3\13\7\7\3"+
    "\15\7\1\3\4\7\3\0\13\3\22\7\3\0\13\3"+
    "\22\7\2\0\14\3\15\7\1\3\3\7\1\3\2\0"+
    "\14\3\64\7\40\0\3\3\1\7\3\3\2\7\1\0"+
    "\2\3\12\0\41\3\4\0\1\3\12\0\6\3\131\7"+
    "\7\3\5\7\2\0\42\7\1\0\1\7\5\3\106\7"+
    "\12\3\37\7\1\3\14\0\4\3\14\0\12\3\12\0"+
    "\36\7\2\3\5\7\13\3\54\7\4\3\32\7\6\3"+
    "\12\0\46\3\27\7\5\0\4\3\65\7\12\0\1\3"+
    "\35\0\2\3\13\0\6\3\12\0\15\3\1\7\10\3"+
    "\16\0\102\3\5\0\57\7\21\0\7\7\4\3\12\0"+
    "\21\3\11\0\14\3\3\0\36\7\15\0\2\7\12\0"+
    "\54\7\16\0\14\3\44\7\24\0\10\3\12\0\3\3"+
    "\3\7\12\0\44\7\2\3\11\7\7\3\53\7\2\3"+
    "\3\7\20\3\3\0\1\3\25\0\4\7\1\0\6\7"+
    "\1\0\2\7\3\0\1\7\5\3\300\7\72\0\1\3"+
    "\5\0\26\7\2\3\6\7\2\3\46\7\2\3\6\7"+
    "\2\3\10\7\1\3\1\7\1\3\1\7\1\3\1\7"+
    "\1\3\37\7\2\3\65\7\1\3\7\7\1\3\1\7"+
    "\3\3\3\7\1\3\7\7\3\3\4\7\2\3\6\7"+
    "\4\3\15\7\5\3\3\7\1\3\7\7\16\3\5\0"+
    "\32\3\5\0\20\3\2\7\23\3\1\7\13\3\5\0"+
    "\1\3\12\0\1\3\1\7\15\3\1\7\20\3\15\7"+
    "\3\3\40\7\20\3\15\0\4\3\1\0\3\3\14\0"+
    "\21\3\1\7\4\3\1\7\2\3\12\7\1\3\1\7"+
    "\3\3\5\7\6\3\1\7\1\3\1\7\1\3\1\7"+
    "\1\3\4\7\1\3\13\7\2\3\4\7\5\3\5\7"+
    "\4\3\1\7\21\3\51\7\u0177\3\57\7\1\3\57\7"+
    "\1\3\205\7\6\3\4\7\3\0\2\7\14\3\46\7"+
    "\1\3\1\7\5\3\1\7\2\3\70\7\7\3\1\7"+
    "\17\3\1\0\27\7\11\3\7\7\1\3\7\7\1\3"+
    "\7\7\1\3\7\7\1\3\7\7\1\3\7\7\1\3"+
    "\7\7\1\3\7\7\1\3\40\0\57\3\1\7\325\3"+
    "\3\7\31\3\11\7\6\0\1\3\5\7\2\3\5\7"+
    "\4\3\126\7\2\3\2\0\2\3\3\7\1\3\132\7"+
    "\1\3\4\7\5\3\53\7\1\3\136\7\21\3\33\7"+
    "\65\3\306\7\112\3\360\7\20\3\215\7\103\3\56\7"+
    "\2\3\15\7\3\3\20\7\12\0\2\7\24\3\57\7"+
    "\1\0\4\3\12\0\1\3\37\7\2\0\120\7\2\0"+
    "\45\3\11\7\2\3\147\7\2\3\65\7\2\3\5\7"+
    "\60\3\13\7\1\0\3\7\1\0\4\7\1\0\27\7"+
    "\5\0\20\3\1\7\7\3\64\7\14\3\2\0\62\7"+
    "\22\0\12\3\12\0\6\3\22\0\6\7\3\3\1\7"+
    "\1\3\2\7\13\0\34\7\10\0\2\3\27\7\15\0"+
    "\14\3\35\7\3\3\4\0\57\7\16\0\16\3\1\7"+
    "\12\0\6\3\5\7\1\0\12\7\12\0\5\7\1\3"+
    "\51\7\16\0\11\3\3\7\1\0\10\7\2\0\2\3"+
    "\12\0\6\3\27\7\3\3\1\7\3\0\62\7\1\0"+
    "\1\7\3\0\2\7\2\0\5\7\2\0\1\7\1\0"+
    "\1\7\30\3\3\7\2\3\13\7\5\0\2\3\3\7"+
    "\2\0\12\3\6\7\2\3\6\7\2\3\6\7\11\3"+
    "\7\7\1\3\7\7\1\3\53\7\1\3\14\7\10\3"+
    "\163\7\10\0\1\3\2\0\2\3\12\0\6\3\244\7"+
    "\14\3\27\7\4\3\61\7\4\3\156\7\2\3\152\7"+
    "\46\3\7\7\14\3\5\7\5\3\1\7\1\0\12\7"+
    "\1\3\15\7\1\3\5\7\1\3\1\7\1\3\2\7"+
    "\1\3\2\7\1\3\154\7\41\3\153\7\22\3\100\7"+
    "\2\3\66\7\50\3\15\7\3\3\20\0\20\3\20\0"+
    "\3\3\2\7\30\3\3\7\31\3\1\7\6\3\5\7"+
    "\1\3\207\7\2\3\1\0\4\3\1\7\13\3\12\0"+
    "\7\3\32\7\4\3\1\7\1\3\32\7\13\3\131\7"+
    "\3\3\6\7\2\3\6\7\2\3\6\7\2\3\3\7"+
    "\3\3\2\7\3\3\2\7\22\3\3\0\4\3\14\7"+
    "\1\3\32\7\1\3\23\7\1\3\2\7\1\3\17\7"+
    "\2\3\16\7\42\3\173\7\105\3\65\7\210\3\1\0"+
    "\202\3\35\7\3\3\61\7\17\3\1\0\37\3\40\7"+
    "\15\3\36\7\5\3\46\7\5\0\5\3\36\7\2\3"+
    "\44\7\4\3\10\7\1\3\5\7\52\3\236\7\2\3"+
    "\12\0\6\3\44\7\4\3\44\7\4\3\50\7\10\3"+
    "\64\7\234\3\67\7\11\3\26\7\12\3\10\7\230\3"+
    "\6\7\2\3\1\7\1\3\54\7\1\3\2\7\3\3"+
    "\1\7\2\3\27\7\12\3\27\7\11\3\37\7\101\3"+
    "\23\7\1\3\2\7\12\3\26\7\12\3\32\7\106\3"+
    "\70\7\6\3\2\7\100\3\1\7\3\0\1\3\2\0"+
    "\5\3\4\0\4\7\1\3\3\7\1\3\35\7\2\3"+
    "\3\0\4\3\1\0\40\3\35\7\3\3\35\7\43\3"+
    "\10\7\1\3\34\7\2\0\31\3\66\7\12\3\26\7"+
    "\12\3\23\7\15\3\22\7\156\3\111\7\67\3\63\7"+
    "\15\3\63\7\15\3\44\7\4\0\10\3\12\0\306\3"+
    "\35\7\12\3\1\7\10\3\26\7\13\0\217\3\27\7"+
    "\11\3\3\0\65\7\17\0\37\3\12\0\17\3\4\0"+
    "\55\7\13\0\2\3\1\0\17\3\1\0\2\3\31\7"+
    "\7\3\12\0\6\3\3\0\44\7\16\0\1\3\12\0"+
    "\4\3\1\7\2\0\11\3\43\7\1\0\2\3\1\7"+
    "\11\3\3\0\60\7\16\0\4\7\4\3\4\0\3\3"+
    "\12\0\1\7\1\3\1\7\43\3\22\7\1\3\31\7"+
    "\14\0\6\3\1\0\101\3\7\7\1\3\1\7\1\3"+
    "\4\7\1\3\17\7\1\3\12\7\7\3\57\7\14\0"+
    "\5\3\12\0\6\3\4\0\1\3\10\7\2\3\2\7"+
    "\2\3\26\7\1\3\7\7\1\3\2\7\1\3\5\7"+
    "\1\3\2\0\1\7\7\0\2\3\2\0\2\3\3\0"+
    "\2\3\1\7\6\3\1\0\5\3\5\7\2\0\2\3"+
    "\7\0\3\3\5\0\213\3\65\7\22\0\4\7\5\3"+
    "\12\0\4\3\1\0\1\7\40\3\60\7\24\0\2\7"+
    "\1\3\1\7\10\3\12\0\246\3\57\7\7\0\2\3"+
    "\11\0\27\3\4\7\2\0\42\3\60\7\21\0\3\3"+
    "\1\7\13\3\12\0\46\3\53\7\15\0\1\7\7\3"+
    "\12\0\66\3\33\7\2\3\17\0\4\3\12\0\306\3"+
    "\54\7\17\0\145\3\100\7\12\0\25\3\1\7\240\3"+
    "\10\7\2\3\47\7\7\0\2\3\7\0\1\7\1\3"+
    "\1\7\1\0\33\3\1\7\12\0\50\7\7\0\1\7"+
    "\4\0\10\3\1\0\10\3\1\7\13\0\56\7\20\0"+
    "\3\3\1\7\42\3\71\7\7\3\11\7\1\3\45\7"+
    "\10\0\1\3\10\0\1\7\17\3\12\0\30\3\36\7"+
    "\2\3\26\0\1\3\16\0\111\3\7\7\1\3\2\7"+
    "\1\3\46\7\6\0\3\3\1\0\1\3\2\0\1\3"+
    "\7\0\1\7\1\0\10\3\12\0\6\3\6\7\1\3"+
    "\2\7\1\3\40\7\5\0\1\3\2\0\1\3\5\0"+
    "\1\7\7\3\12\0\u0136\3\23\7\4\0\346\3\4\7"+
    "\37\3\232\7\146\3\157\7\21\3\304\7\274\3\57\7"+
    "\1\3\11\0\307\3\107\7\271\3\71\7\7\3\37\7"+
    "\1\3\12\0\146\3\36\7\2\3\5\0\13\3\60\7"+
    "\7\0\11\3\4\7\14\3\12\0\11\3\25\7\5\3"+
    "\23\7\260\3\100\7\200\3\113\7\4\3\1\0\1\7"+
    "\67\0\7\3\4\0\15\7\100\3\2\7\1\3\1\7"+
    "\34\3\370\7\10\3\363\7\15\3\37\7\61\3\3\7"+
    "\21\3\4\7\10\3\u018c\7\4\3\153\7\5\3\15\7"+
    "\3\3\11\7\7\3\12\7\3\3\2\0\1\3\4\0"+
    "\301\3\5\0\3\3\26\0\2\3\7\0\36\3\4\0"+
    "\224\3\3\0\273\3\125\7\1\3\107\7\1\3\2\7"+
    "\2\3\1\7\2\3\2\7\2\3\4\7\1\3\14\7"+
    "\1\3\1\7\1\3\7\7\1\3\101\7\1\3\4\7"+
    "\2\3\10\7\1\3\7\7\1\3\34\7\1\3\4\7"+
    "\1\3\5\7\1\3\1\7\3\3\7\7\1\3\u0154\7"+
    "\2\3\31\7\1\3\31\7\1\3\37\7\1\3\31\7"+
    "\1\3\37\7\1\3\31\7\1\3\37\7\1\3\31\7"+
    "\1\3\37\7\1\3\31\7\1\3\10\7\2\3\151\0"+
    "\4\3\62\0\10\3\1\0\16\3\1\0\26\3\5\0"+
    "\1\3\17\0\120\3\7\0\1\3\21\0\2\3\7\0"+
    "\1\3\2\0\1\3\5\0\325\3\55\7\3\3\7\0"+
    "\7\7\2\3\12\0\4\3\1\7\u0171\3\54\7\16\0"+
    "\5\3\306\7\13\3\7\0\51\3\104\7\7\0\1\7"+
    "\4\3\12\0\u0156\3\1\7\117\3\4\7\1\3\33\7"+
    "\1\3\2\7\1\3\1\7\2\3\1\7\1\3\12\7"+
    "\1\3\4\7\1\3\1\7\1\3\1\7\6\3\1\7"+
    "\4\3\1\7\1\3\1\7\1\3\1\7\1\3\3\7"+
    "\1\3\2\7\1\3\1\7\2\3\1\7\1\3\1\7"+
    "\1\3\1\7\1\3\1\7\1\3\1\7\1\3\2\7"+
    "\1\3\1\7\2\3\4\7\1\3\7\7\1\3\4\7"+
    "\1\3\4\7\1\3\1\7\1\3\12\7\1\3\21\7"+
    "\5\3\3\7\1\3\5\7\1\3\21\7\104\3\327\7"+
    "\51\3\65\7\13\3\336\7\2\3\u0182\7\16\3\u0131\7"+
    "\37\3\36\7\343\3\1\0\36\3\140\0\200\3\360\0"+
    "\20\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[29952];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\1\3\1\1"+
    "\2\3\2\6\20\5\1\1\1\7\1\10\1\11\2\0"+
    "\1\2\1\12\1\0\15\5\1\3\15\5\1\13\1\14"+
    "\1\15\1\16\3\0\1\6\15\5\1\3\12\5\1\0"+
    "\1\2\1\0\1\12\15\5\1\17\33\5";

  private static int [] zzUnpackAction() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\146\0\231\0\314\0\146\0\377"+
    "\0\146\0\u0132\0\u0165\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u0264"+
    "\0\u0297\0\u02ca\0\u02fd\0\u0330\0\u0363\0\u0396\0\u03c9\0\u03fc"+
    "\0\u042f\0\u0462\0\u0495\0\u04c8\0\u04fb\0\u052e\0\u0561\0\u0594"+
    "\0\146\0\u05c7\0\u05fa\0\u062d\0\u0660\0\u0693\0\u06c6\0\u06f9"+
    "\0\u072c\0\u075f\0\u0792\0\u07c5\0\u07f8\0\u082b\0\u085e\0\u0891"+
    "\0\u08c4\0\u08f7\0\u092a\0\u095d\0\377\0\u0990\0\u09c3\0\u09f6"+
    "\0\u0a29\0\u0a5c\0\u0a8f\0\u0ac2\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e"+
    "\0\u0bc1\0\u0bf4\0\146\0\146\0\146\0\146\0\u0c27\0\u0c5a"+
    "\0\u0c8d\0\u06c6\0\u0cc0\0\u0cf3\0\u0d26\0\u0d59\0\u0d8c\0\u0dbf"+
    "\0\u0df2\0\u0e25\0\u0e58\0\u0e8b\0\u0ebe\0\u0ef1\0\u0f24\0\u0f57"+
    "\0\u0f8a\0\u0fbd\0\u0ff0\0\u1023\0\u1056\0\u1089\0\u10bc\0\u10ef"+
    "\0\u1122\0\u1155\0\u1188\0\u0c27\0\u11bb\0\u11bb\0\u11ee\0\u1221"+
    "\0\u1254\0\u1287\0\u12ba\0\u12ed\0\u1320\0\u1353\0\u1386\0\u13b9"+
    "\0\u13ec\0\u141f\0\u1452\0\377\0\u1485\0\u14b8\0\u14eb\0\u151e"+
    "\0\u1551\0\u1584\0\u15b7\0\u15ea\0\u161d\0\u1650\0\u1683\0\u16b6"+
    "\0\u16e9\0\u171c\0\u174f\0\u1782\0\u17b5\0\u17e8\0\u181b\0\u184e"+
    "\0\u1881\0\u18b4\0\u18e7\0\u191a\0\u194d\0\u1980\0\u19b3";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\3\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\11\1\13\1\11\1\14\1\15\1\16\1\6"+
    "\5\10\1\17\1\20\1\21\1\10\1\3\1\10\1\22"+
    "\1\23\1\24\1\25\1\26\2\10\1\27\3\10\1\30"+
    "\1\10\1\31\1\32\1\33\1\34\1\10\1\35\1\36"+
    "\2\10\1\37\2\40\1\3\1\40\1\3\1\40\1\41"+
    "\23\40\1\42\30\40\65\0\1\4\100\0\1\11\42\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\27\10\12\0\1\11\67\0\2\43\55\0\1\44\2\0"+
    "\1\45\61\0\1\46\1\0\2\16\11\0\1\47\26\0"+
    "\1\47\16\0\1\46\1\0\2\16\43\0\1\10\6\0"+
    "\1\10\6\0\2\10\1\0\11\10\1\0\4\10\1\50"+
    "\22\10\1\0\1\10\6\0\1\10\6\0\2\10\1\0"+
    "\11\10\1\0\17\10\1\51\7\10\1\0\1\10\6\0"+
    "\1\10\6\0\2\10\1\0\11\10\1\0\4\10\1\52"+
    "\22\10\1\0\1\10\6\0\1\10\6\0\2\10\1\0"+
    "\11\10\1\0\15\10\1\53\1\10\1\54\1\10\1\55"+
    "\5\10\1\0\1\10\6\0\1\10\6\0\2\10\1\0"+
    "\11\10\1\0\12\10\1\56\2\10\1\57\11\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\15\10\1\60\3\10\1\55\5\10\1\0\1\10\6\0"+
    "\1\10\6\0\2\10\1\0\11\10\1\0\12\10\1\61"+
    "\12\10\1\62\1\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\1\63\14\10\1\64\11\10"+
    "\1\0\1\10\6\0\1\10\6\0\2\10\1\0\11\10"+
    "\1\0\5\10\1\65\5\10\1\66\1\67\4\10\1\70"+
    "\5\10\1\0\1\10\6\0\1\10\6\0\2\10\1\0"+
    "\11\10\1\0\4\10\1\71\15\10\1\72\4\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\17\10\1\73\2\10\1\74\4\10\1\0\1\10\6\0"+
    "\1\10\6\0\2\10\1\0\11\10\1\0\4\10\1\75"+
    "\22\10\1\0\1\10\6\0\1\10\6\0\2\10\1\0"+
    "\11\10\1\0\21\10\1\76\5\10\1\0\1\10\6\0"+
    "\1\10\6\0\2\10\1\0\11\10\1\0\7\10\1\77"+
    "\7\10\1\100\7\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\15\10\1\101\11\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\7\10\1\102\17\10\63\0\1\11\2\40\1\0\1\40"+
    "\1\0\1\40\1\0\23\40\1\0\30\40\6\0\1\103"+
    "\40\0\1\104\2\0\1\105\1\0\1\106\22\0\1\46"+
    "\1\0\2\43\43\0\12\107\1\110\50\107\2\45\1\4"+
    "\1\45\1\5\56\45\16\0\2\46\3\0\1\111\13\0"+
    "\1\111\41\0\2\112\1\0\3\112\7\0\6\112\22\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\24\10\1\113\2\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\10\10\1\114\16\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\1\115\26\10\1\0\1\10\6\0\1\10\6\0\2\10"+
    "\1\0\11\10\1\0\15\10\1\116\11\10\1\0\1\10"+
    "\6\0\1\10\6\0\2\10\1\0\11\10\1\0\4\10"+
    "\1\117\22\10\1\0\1\10\6\0\1\10\6\0\2\10"+
    "\1\0\11\10\1\0\15\10\1\120\11\10\1\0\1\10"+
    "\6\0\1\10\6\0\2\10\1\0\11\10\1\0\1\121"+
    "\26\10\1\0\1\10\6\0\1\10\6\0\2\10\1\0"+
    "\11\10\1\0\14\10\1\122\12\10\1\0\1\10\6\0"+
    "\1\10\6\0\2\10\1\0\11\10\1\0\22\10\1\123"+
    "\4\10\1\0\1\10\6\0\1\10\6\0\2\10\1\0"+
    "\11\10\1\0\20\10\1\124\6\10\1\0\1\10\6\0"+
    "\1\10\6\0\2\10\1\0\11\10\1\0\21\10\1\125"+
    "\5\10\1\0\1\10\6\0\1\10\6\0\2\10\1\0"+
    "\11\10\1\0\12\10\1\126\14\10\1\0\1\10\6\0"+
    "\1\10\6\0\2\10\1\0\11\10\1\0\17\10\1\65"+
    "\7\10\1\0\1\10\6\0\1\10\6\0\2\10\1\0"+
    "\11\10\1\0\16\10\1\127\10\10\1\0\1\10\6\0"+
    "\1\10\6\0\2\10\1\0\11\10\1\0\21\10\1\130"+
    "\5\10\1\0\1\10\6\0\1\10\6\0\2\10\1\0"+
    "\11\10\1\0\15\10\1\131\11\10\1\0\1\10\6\0"+
    "\1\10\6\0\2\10\1\0\11\10\1\0\24\10\1\65"+
    "\2\10\1\0\1\10\6\0\1\10\6\0\2\10\1\0"+
    "\11\10\1\0\12\10\1\116\14\10\1\0\1\10\6\0"+
    "\1\10\6\0\2\10\1\0\11\10\1\0\10\10\1\132"+
    "\4\10\1\133\11\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\1\10\1\134\25\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\21\10\1\135\5\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\17\10\1\136\7\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\10\10\1\137\16\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\22\10\1\140\4\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\10\10\1\141\16\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\10\10\1\142\16\10\1\0"+
    "\12\107\1\143\62\107\1\143\2\107\1\144\45\107\13\0"+
    "\1\145\2\0\2\146\43\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\1\147\10\10\1\0\27\10\1\0\1\10"+
    "\6\0\1\10\6\0\2\10\1\0\11\10\1\0\14\10"+
    "\1\150\12\10\1\0\1\10\6\0\1\10\6\0\2\10"+
    "\1\0\11\10\1\0\3\10\1\151\23\10\1\0\1\10"+
    "\6\0\1\10\6\0\2\10\1\0\11\10\1\0\12\10"+
    "\1\65\14\10\1\0\1\10\6\0\1\10\6\0\2\10"+
    "\1\0\11\10\1\0\1\152\26\10\1\0\1\10\6\0"+
    "\1\10\6\0\2\10\1\0\11\10\1\0\10\10\1\65"+
    "\16\10\1\0\1\10\6\0\1\10\6\0\2\10\1\0"+
    "\11\10\1\0\20\10\1\137\6\10\1\0\1\10\6\0"+
    "\1\10\6\0\2\10\1\0\11\10\1\0\21\10\1\153"+
    "\5\10\1\0\1\10\6\0\1\10\6\0\2\10\1\0"+
    "\11\10\1\0\1\10\1\142\25\10\1\0\1\10\6\0"+
    "\1\10\6\0\2\10\1\0\11\10\1\0\4\10\1\65"+
    "\22\10\1\0\1\10\6\0\1\10\6\0\2\10\1\0"+
    "\11\10\1\0\4\10\1\154\22\10\1\0\1\10\6\0"+
    "\1\10\6\0\2\10\1\0\11\10\1\0\20\10\1\140"+
    "\6\10\1\0\1\10\6\0\1\10\6\0\2\10\1\0"+
    "\11\10\1\0\12\10\1\155\14\10\1\0\1\10\6\0"+
    "\1\10\6\0\2\10\1\0\11\10\1\0\4\10\1\156"+
    "\22\10\1\0\1\10\6\0\1\10\6\0\2\10\1\0"+
    "\11\10\1\0\1\10\1\65\1\10\1\65\23\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\23\10\1\157\3\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\21\10\1\160\5\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\12\10\1\161\14\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\22\10\1\162\4\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\10\10\1\163\16\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\20\10\1\65\6\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\4\10\1\164\22\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\3\10\1\65\23\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\12\10\1\124\14\10\1\0\12\107\1\143\2\107\1\4"+
    "\45\107\16\0\2\146\43\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\17\10\1\165\7\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\21\10\1\65\5\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\3\10\1\166\1\167\4\10\1\0\27\10"+
    "\1\0\1\10\6\0\1\10\6\0\2\10\1\0\11\10"+
    "\1\0\11\10\1\65\15\10\1\0\1\10\6\0\1\10"+
    "\6\0\2\10\1\0\11\10\1\0\10\10\1\170\16\10"+
    "\1\0\1\10\6\0\1\10\6\0\2\10\1\0\11\10"+
    "\1\0\14\10\1\171\12\10\1\0\1\10\6\0\1\10"+
    "\6\0\2\10\1\0\11\10\1\0\4\10\1\172\22\10"+
    "\1\0\1\10\6\0\1\10\6\0\2\10\1\0\11\10"+
    "\1\0\17\10\1\173\7\10\1\0\1\10\6\0\1\10"+
    "\6\0\2\10\1\0\11\10\1\0\1\174\26\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\4\10\1\175\22\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\10\10\1\176\16\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\17\10\1\177\7\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\14\10\1\200\12\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\17\10\1\201\7\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\14\10\1\202\12\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\10\10\1\203\16\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\14\10\1\204\12\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\3\10\1\137\23\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\13\10\1\205\13\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\5\10\1\206\21\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\21\10\1\124\5\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\2\10\1\207\24\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\2\10\1\65\24\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\14\10\1\65\12\10\1\0\1\10\6\0\1\10\6\0"+
    "\2\10\1\0\11\10\1\0\6\10\1\65\20\10\1\0"+
    "\1\10\6\0\1\10\6\0\2\10\1\0\11\10\1\0"+
    "\1\210\26\10\1\0\1\10\6\0\1\10\6\0\2\10"+
    "\1\0\11\10\1\0\21\10\1\211\5\10\1\0\1\10"+
    "\6\0\1\10\6\0\2\10\1\0\11\10\1\0\14\10"+
    "\1\124\12\10\1\0\1\10\6\0\1\10\6\0\2\10"+
    "\1\0\11\10\1\0\22\10\1\124\4\10\1\0\1\10"+
    "\6\0\1\10\6\0\2\10\1\0\11\10\1\0\4\10"+
    "\1\212\22\10\1\0\1\10\6\0\1\10\6\0\2\10"+
    "\1\0\11\10\1\0\1\213\26\10\1\0\1\10\6\0"+
    "\1\10\6\0\2\10\1\0\11\10\1\0\21\10\1\214"+
    "\5\10\1\0\1\10\6\0\1\10\6\0\2\10\1\0"+
    "\11\10\1\0\26\10\1\65\1\0\1\10\6\0\1\10"+
    "\6\0\2\10\1\0\11\10\1\0\4\10\1\215\22\10"+
    "\1\0\1\10\6\0\1\10\6\0\2\10\1\0\11\10"+
    "\1\0\14\10\1\216\12\10\1\0\1\10\6\0\1\10"+
    "\6\0\2\10\1\0\11\10\1\0\2\10\1\124\24\10"+
    "\1\0\1\10\6\0\1\10\6\0\2\10\1\0\11\10"+
    "\1\0\4\10\1\141\22\10\1\0\1\10\6\0\1\10"+
    "\6\0\2\10\1\0\11\10\1\0\6\10\1\217\20\10"+
    "\1\0\1\10\6\0\1\10\6\0\2\10\1\0\11\10"+
    "\1\0\21\10\1\137\5\10\1\0\1\10\6\0\1\10"+
    "\6\0\2\10\1\0\11\10\1\0\4\10\1\64\22\10"+
    "\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6630];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\2\1\1\11\1\1\1\11\27\1\1\11"+
    "\1\1\2\0\2\1\1\0\33\1\4\11\3\0\31\1"+
    "\1\0\1\1\1\0\52\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    StringBuffer string = new StringBuffer();
  public Symbol token(int tokenType){
      System.out.println(yytext());
      return new Symbol(tokenType, yytext());
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.print(yytext());
            }
            // fall through
          case 16: break;
          case 2:
            { /* ignore */
            }
            // fall through
          case 17: break;
          case 3:
            { System.out.println(yytext());
            }
            // fall through
          case 18: break;
          case 4:
            { string.setLength(0); yybegin(STRING);
            }
            // fall through
          case 19: break;
          case 5:
            { System.out.println("T_ID "+yytext());
            }
            // fall through
          case 20: break;
          case 6:
            { System.out.println("T_INTLITERAL "+yytext());
            }
            // fall through
          case 21: break;
          case 7:
            { string.append( yytext() );
            }
            // fall through
          case 22: break;
          case 8:
            { yybegin(YYINITIAL);
                            System.out.println("T_STRINGLITERAL \""+string.toString()+"\"");
                            string = new StringBuffer();
            }
            // fall through
          case 23: break;
          case 9:
            { string.append("\\");
            }
            // fall through
          case 24: break;
          case 10:
            { System.out.println("T_DOUBLELITERAL "+yytext());
            }
            // fall through
          case 25: break;
          case 11:
            { string.append("\"");
            }
            // fall through
          case 26: break;
          case 12:
            { string.append("\n");
            }
            // fall through
          case 27: break;
          case 13:
            { string.append("\r");
            }
            // fall through
          case 28: break;
          case 14:
            { string.append("\t");
            }
            // fall through
          case 29: break;
          case 15:
            { System.out.println("T_BOOLEANLITERAL "+yytext());
            }
            // fall through
          case 30: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java Scanner [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Scanner scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Scanner(reader);
          while ( !scanner.zzAtEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
